---
- name: restart ollama
  ansible.builtin.shell: |
    set -e
    systemctl daemon-reload
    systemctl restart ollama
  become: true
  when: ansible_facts['service_mgr'] == 'systemd'
  changed_when: true
